### ISSUE TITLE
Crashes with Spartan Weaponry.

### ISSUE THREAD

**Issue by MagmaSlime123** [kappa-maintainer/Hesperus#3]
See https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry/issues/295 for more info.
Both this and the original version cause this issue.

**Comment by kappa-maintainer** [comment]
Can't reproduce and looks like a mixin compat error, try installing latest mixinbooter

**Comment by MagmaSlime123** [comment]
Fixed. Curse page never mentions MixinBooter anywhere.

**Comment by kappa-maintainer** [comment]
It is in dependency page the whole time, but I guess I better to put it in description
