### ISSUE TITLE
Breaking multiple blocks at once can cause lighting to get "stuck"

### ISSUE THREAD

**Issue by ghost** [kappa-maintainer/Hesperus#9]
I was playing on 1.12.2 and I noticed that breaking multiple blocks with OreExcavation/VeinMiner can cause lighting to get "stuck" when Hesperus is installed  (doesn't happen with Phosphor). It also seems like the issue is worse and more common if other mods are installed.

Hesperus (no other mods installed):
![2023-07-27_17 22 16](https://github.com/kappa-maintainer/Hesperus/assets/63958709/0cdb5ae9-d901-43ba-ab07-329a0b2fa892)

Hesperus and a whole bunch of mods:
![2023-07-27_17 11 52](https://github.com/kappa-maintainer/Hesperus/assets/63958709/3aa612a1-6788-4492-b1b3-b96c5ddc98d3)

**Comment by kappa-maintainer** [comment]
I will take a look

**Comment by kappa-maintainer** [comment]
Please try this build
[debug.zip](https://github.com/kappa-maintainer/Hesperus/files/12448145/debug.zip)

**Comment by ghost** [comment]
> Please try this build [debug.zip](https://github.com/kappa-maintainer/Hesperus/files/12448145/debug.zip)

The issue seems to be gone now, thanks!

**Comment by Desoroxxx** [comment]
Did you forget to commit to GitHub?

**Comment by kappa-maintainer** [comment]
> Did you forget to commit to GitHub?

Oops, forgot that
